<a href="https://colab.research.google.com/github/dl-bk/AI_1/blob/master/lab1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [2]:
import numpy as np

# Завдання 1
Створіть масив з елементами від 1 до 12. Виведіть розмір та тип масиву

In [10]:
a = np.arange(1,13)


print(a.shape)
print(type(a))

(12,)
<class 'numpy.ndarray'>


# Завдання 2
Зробіть на основі попереднього масиву матрицю з 4 стовчиками. Змініть тип даних матриці на float32. Виведіть транспоновану матрицю.

In [9]:
reshape_matrix = a.reshape((3,4))
reshape_matrix = reshape_matrix.astype('float32')

print(reshape_matrix.T)

[[ 1.  5.  9.]
 [ 2.  6. 10.]
 [ 3.  7. 11.]
 [ 4.  8. 12.]]


#Завдання 3
Створіть матрицю 8х8 з 0 та 1 розміщеними в шаховому порядку

In [11]:
matrix = np.zeros((8,8), dtype=int)
matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1

print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# Завдання 4
Створіть випадкову матрицю 4х3. Знайдіть суму елементів в стовпчиках\рядках\усій матриці

In [13]:
a = np.random.random((4,3))
print(a)

sum_cols = np.sum(a, axis = 0)
sum_rows = np.sum(a, axis = 1)
total = np.sum(a)
print(sum_cols)
print(sum_rows)
print(total)

[[0.12168656 0.1756745  0.1362271 ]
 [0.22617766 0.70604581 0.05983007]
 [0.08764068 0.26338141 0.82993264]
 [0.70343958 0.86699549 0.45424941]]
[1.13894448 2.01209722 1.48023922]
[0.43358816 0.99205354 1.18095473 2.02468448]
4.6312809162668325


# Завдання 5
У попередній матриці від кожного рядка відніміть максимальний елемент цього рядка

# Завдання 6
Є дані про вагу контейнерів для перевезення на кораблі: дрібний - 5 т,  малий - 10 т, середній - 25 т, великий - 40 т. На кораблі розміщено 20 дрібних, 5 малих, 10 середніх та 4 великих контейнерів. Знайти масу вантажу.

# Завдання 7
Тепер у нас декілька кораблів. Напишіть код для обчислення вантажу на кожному кораблі.